### ISSUE TITLE
Accounts should contain public_wallet addresses

### ISSUE THREAD

**Issue by dexterlohnes** [shredding/stellar-bot#17]
Per our discussion @shredding, it'd be great if we could link Accounts to public wallet addresses.

## Proposal

1) Account would be defined as follows
- adapter: String,
- uniqueId: String,
- createdAt: String,
- updatedAt: String,
- balance: String,
- **publicWalletAddr**: String _(NOTE: Whatever the name is, it should be clear to developers this is NOT a stored secret key)._

2) Introduce a concept of "registration" whereby an adapter-unique ID pair is linked to a public wallet address.

> ex: Unregistered Account
>  {
>     adapter: 'reddit',
>     uniqueId: 'someUserName',
>     publicWalletAddr: null
>   }

> ex: Registered Account
>  {
>     adapter: 'reddit',
>     uniqueId: 'someUserName',
>     publicWalletAddr: 'U01idjf02idjasd02udjasdflkj'
>   }

### Adapters
Adapters would be responsible for registering users. For reference, the paradigm I'm proposing necessitates three slash commands on Slack: 
    - /tip {@username} {amount}xlm
    - /withdrawal {amount}xlm _{~optional public-wallet-address}_
    - /register {public-wallet-address} // unique user ID is pulled from info included in POST req

### Accounts
Accounts would include an "isRegistered" get function which would simply tell the developer if the public wallet address field is filled in, which allows for meaningful logic branching. 

--------------------------

This would change a decent amount for sure, but I think at the end of the day it'd allow for a much more usable system moving forward across all platforms.

**Comment by shredding** [comment]
I would like to see this as some kind of account settings that are optional (adapters can opt to use it or not). It's basically the same you proposed, but a bit more general and will allow us to add more options (specifically for https://github.com/shredding/stellar-bot/issues/19, see my proposal there):

1. Add `withdrawalAddress` to the account model which can be null (add a check for a valid address in the `beforeSave` hook of the model.

2. Add a `setAccountOptions(options)` to the abstract adapter that accepts an option object (`{withdrawalAddress: 'somePublicAddress'}`). This method can then be expanded to accept more options in the future. Validations should be in there as well. The method should give back an object where the key is the requested option and the value is the set value (the address). It could throw a catchable error if stuff goes wrong (e.g. if it's not a valid stellar address).

3. Make `address` optional in the [receiveWithdrawalRequest]https://github.com/shredding/stellar-bot/blob/master/src/adapters/abstract.js#L128-L143) tip object. If it's not given, try to fetch it from the account. Throw an error (not an event/hook) if account does not have a withdrawalAddress.

4. The `withdraw` method in `https://github.com/shredding/stellar-bot/blob/master/src/adapters/abstract.js#L165` should still require an address, so the adapter should figure out if we have an address to use before it's called. In general the adapter should figure out if an option is required, how to handle it etc.

5. You can then decide how you trigger the call within the slack bot and while `/register` is possible, i would use a clear naming like `/set-withdrawal-address` or sth like that.

What do u think?

**Comment by shredding** [comment]
... we could think of an option to request this settings, but we can make a separate ticket for this, something like `getAccountOptions(['withdrawalAddress'])`.

**Comment by dexterlohnes** [comment]
@shredding What should I be doing if the public wallet address provided fails validation according to the Stellar SDK in Account::beforeSave()? Should I throw an error? Just not set the public wallet address?

**Comment by shredding** [comment]
An error is the better option i guess, so you can catch it and give an appropriate error message.

I'd name it `withdrawalAddress`, because it's clear by the validation that it's a public address, but we might introduce other addresses (e.g. depositAddress, to get rid of the memoId) in the future.

**Comment by shredding** [comment]
I see your PR is WIP, so i won't comment on it yet, right?

But one thing i noticed is that it spreads the file structure quite a bit, can you put everything related to slack into a folder like this:

```
src/adapters/slack/index.js => yourAdapter
src/adapters/slack/utils.js => utils
...
etc
```
Adapters should be a package in the adapter folder and not spread around everywhere.

**Comment by dexterlohnes** [comment]
Comments would be appreciated. It should be fully functioning.

**Comment by dexterlohnes** [comment]
Commits 1c6f050 and 43aa428 fix the issues with file structure

**Comment by shredding** [comment]
closed, as slack bot moved to a fork
