### ISSUE TITLE
How do I withdraw my funds from stellar_bot - user doesn't exist?

### ISSUE THREAD

**Issue by tallship** [shredding/stellar-bot#30]
Hello, as per the instructions at Lumenauts which you link to in the readme.md, I attempted to withdraw my funds once I saw that it didn't work. Then I attempted to check my balance. In both cases, the Reddit message system error-ed out saying that the user (stellar_bot) doesn't exist:
https://www.lumenauts.com/tutorials/how-to-tip-with-the-stellar-subreddit-tipping-bot

I really like the notion of a tipbot, much more intriguing than Reddit's 'Coins", but if it doesn't work, how do I get my money back?

**Comment by shredding** [comment]
The bot is no longer operating. You can send me a private message from your reddit account to the-dark-coder and I'll manually pay you out.
